import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import RiskPill from '../components/RiskPill.jsx'
import { getDashboardSummary, getReferrals, searchPatients } from '../lib/patientApi.js'

export default function WorkerDashboard(){
 const [summary,setSummary]=useState(null); const [patients,setPatients]=useState([]); const [referrals,setReferrals]=useState([]); const [error,setError]=useState('')
 useEffect(()=>{(async()=>{try{const [s,p,r]=await Promise.all([getDashboardSummary().catch(()=>null),searchPatients(''),getReferrals().catch(()=>[])]);setSummary(s);setPatients(p.slice(0,10));setReferrals(r.slice(0,5))}catch(e){setError(e.message)}})()},[])
 return <div><div className="flex flex-wrap justify-between items-center gap-4 mb-6"><div><h1 className="text-2xl m-0">Healthcare worker dashboard</h1><div className="text-sm text-ink-soft mt-0.5">Live backend data</div></div><Link to="/dashboard/worker/register" className="inline-block font-semibold text-sm px-4 py-2.5 rounded-md bg-primary text-white no-underline">Register new patient</Link></div>{error&&<p className="text-sm text-accent mb-4">{error}</p>}<div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-7"><KpiCard label="Patients" value={summary?.total_patients??patients.length}/><KpiCard label="High risk" value={summary?.high_risk_count??'—'} valueClass="text-risk-high"/><KpiCard label="Moderate risk" value={summary?.moderate_risk_count??'—'} valueClass="text-risk-mid"/><KpiCard label="Pending referrals" value={summary?.pending_referrals??referrals.length}/></div><div className="grid lg:grid-cols-[1.4fr_1fr] gap-5"><div className="bg-white border border-line rounded-lg p-5"><h2 className="text-base mb-3.5">Recent patients</h2><table className="w-full border-collapse text-sm"><thead><tr>{['Name','Age','District'].map(h=><th key={h} className="text-left text-xs text-ink-soft border-b border-line pb-2">{h}</th>)}</tr></thead><tbody>{patients.map(p=><tr key={p.id}><td className="py-2.5 border-b border-line">{p.name}</td><td className="py-2.5 border-b border-line">{p.age??'—'}</td><td className="py-2.5 border-b border-line">{p.district??'—'}</td></tr>)}</tbody></table></div><div className="bg-white border border-line rounded-lg p-5"><h2 className="text-base mb-3.5">Referral queue</h2>{referrals.length?<ul className="list-none p-0 m-0 flex flex-col gap-2.5">{referrals.map(r=><li key={r.id} className="border border-line rounded-md px-3 py-2.5 text-sm"><strong>{r.patient_name||r.patient_id}</strong><div className="text-xs text-ink-soft">{r.status}</div></li>)}</ul>:<p className="text-sm text-ink-soft">No pending referrals.</p>}</div></div></div>
}
function KpiCard({label,value,valueClass='text-primary-dark'}){return <div className="bg-white border border-line rounded-lg px-4 py-4"><div className="text-sm text-ink-soft mb-1.5">{label}</div><div className={`font-serif text-2xl font-semibold ${valueClass}`}>{value}</div></div>}
